### ISSUE TITLE
karpenter sometimes evicting the pods even though they have the do-not-evict annotation when consolidation enabled

### ISSUE THREAD

**Issue by brainiac84** [aws/karpenter#3594]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.25.5-eks-c248520

### Expected Behavior

Do not evict the pods if `do-not-evict` annotation is set and when consolidation enabled

### Actual Behavior

karpenter sometimes evicting the pods(spawned by the job) which have the `do-not-evict` annotation _only_ when consolidation enabled

### Steps to Reproduce the Problem

Trigger around 60+ jobs to run in parallel, where is the pods have the `do-not-evict` annotation

### Resource Specs and Logs

full job spec:
```yaml
   apiVersion: batch/v1
    kind: Job
    metadata:
      generateName: placeholder # it'll be replaced with jobID
      labels:
        helm.sh/chart: workers-0.1.0
        app.kubernetes.io/name: "workers"
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      activeDeadlineSeconds: 86400
      ttlSecondsAfterFinished: 7200
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: workers-job
            app.kubernetes.io/instance: release-name
          annotations:
            config.cordial.com/job-template: default
            app.gitlab.com/app: cordialexperiences-apps-core
            app.gitlab.com/env: staging
            karpenter.sh/do-not-evict: "true"
            linkerd.io/inject: enabled
        spec:
          terminationGracePeriodSeconds: 60
          restartPolicy: Never
          serviceAccountName: workers
          securityContext:
            sysctls:
            - name: net.ipv4.ip_local_port_range
              value: 10000 60999
          volumes:
            
            - name: vault-agent-config
              configMap:
                defaultMode: 420
                name: vault-agent-config
            - name: vault-cert
              configMap:
                defaultMode: 420
                name: vault-agent-config
                items:
                  - key: vault-ca.pem
                    path: vault-ca.pem
            - name: vault-token
              emptyDir:
                medium: Memory
            - name: consul-template
              emptyDir: {}
            - name: consul-template-out
              emptyDir: {}
            - name: cordial-data
              emptyDir: {}
            - name: temp
              emptyDir: {}
            - name: logs
              emptyDir: {}
            - name: logs-local
              emptyDir: {}
            - name: logrotate-conf
              configMap:
                defaultMode: 0644
                name: logrotate-conf
                items:
                  - key: logrotate.conf
                    path: logrotate.conf
            - name: statsd-exporter-config
              configMap:
                name: statsd-exporter-config
            - name: exit-notice
              emptyDir: {}
            - name: workers-clusters-creds
              csi:
                driver: 'secrets-store.csi.k8s.io'
                readOnly: true
                volumeAttributes:
                  secretProviderClass: 'workers-clusters-creds'
            
            - name: php-ini-settings
              configMap:
                defaultMode: 0644
                name: php-ini-settings
                items:
                - key: zz-custom.ini
                  path: zz-custom.ini
            - name: php-opcache
              emptyDir:
                medium: Memory
            - name: consul-template-secret
              csi:
                driver: 'secrets-store.csi.k8s.io'
                readOnly: true
                volumeAttributes:
                  secretProviderClass: 'workers-consul-template'
          initContainers:
            - name: config-template-copy
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/cordial/core:cli-r-20210907.1568109017.stg"
              imagePullPolicy: IfNotPresent
              command:
                - /init
              args:
                - cp
                - /var/cordial/config.ini.tpl
                - /consul-template/config.ini.tpl
              volumeMounts:
                - mountPath: /consul-template
                  name: consul-template
              resources:
                requests:
                  memory: 10Mi
                  cpu: 10m
            - name: vault-agent-init
              args:
                - agent
                - -config=/etc/vault/vault-agent-config.hcl
                - -exit-after-auth
              env:
                - name: VAULT_ADDR
                  value: "[REDACTED]"
                - name: VAULT_CAPATH
                  value: "/etc/ssl/certs"
                - name: SKIP_SETCAP
                  value: "true"
                - name: SKIP_CHOWN
                  value: "true"
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/vault:1.11.7"
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 100
                runAsGroup: 1000
              volumeMounts:
                - mountPath: /etc/vault
                  name: vault-agent-config
                  readOnly: true
                - mountPath: /etc/ssl/certs/vault-ca.pem
                  name: vault-cert
                  readOnly: true
                  subPath: vault-ca.pem
                - mountPath: /home/vault
                  name: vault-token
              resources:
                limits:
                  cpu: 200m
                requests:
                  cpu: 5m
                  ephemeral-storage: 300Ki
                  memory: 150Mi
            - name: consul-template-init
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/cordial/consul-template:main-c1b25503"
              imagePullPolicy: IfNotPresent
              args:
                - /bin/bash
                - '-ec'
                - |
                  /usr/local/bin/consul-template \
                  -consul-addr=http://consul-client.consul.svc.cluster.local:8500 \
                  -vault-addr="[REDACTED]" \
                  -vault-ssl-ca-path=/etc/ssl/certs \
                  -log-level=$(LOG_LEVEL) \
                  -max-stale=10m \
                  -consul-token-file=/mnt/secret/acl-token \
                  -template "/consul-template/config.ini.tpl:/consul-template-out/config.ini" \
                  -once
              env:
                # we avoid a global value here since it is different per component
                - name: APP_NAME
                  value: "k8s-jobs"
                - name: K8S_LOGIN
                  value: "false"
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: LOG_LEVEL
                  value: "info"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: VAULT_WAIT
                  value: "false"
                - name: VAULT_K8S_AUTH_ROLE_NAME
                  value: "core-app"
                - name: VAULT_K8S_SERVICE_MOUNT_PATH
                  value: "kubernetes"
                - name: DATADOG_HOST
                  value: "127.0.0.1"
                - name: DATADOG_PORT
                  value: "9125"
                - name: "AVAILABILITY_ZONE"
                  value: "us-west-2a"
                - name: "CONSUL_AUTH_METHOD_NAME"
                  value: "kubernetes"
              volumeMounts:
                - mountPath: /consul-template
                  name: consul-template
                - mountPath: /consul-template-out
                  name: consul-template-out
                - mountPath: /home/vault
                  name: vault-token
                - mountPath: /etc/ssl/certs/vault-ca.pem
                  name: vault-cert
                  readOnly: true
                  subPath: vault-ca.pem
                - name: consul-template-secret
                  mountPath: '/mnt/secret'
                  readOnly: true
              resources:
                limits:
                  cpu: 50m
                requests:
                  cpu: 5m
                  ephemeral-storage: 300Ki
                  memory: 50Mi
          containers:
            - name: workers
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/cordial/core:cli-r-20210907.1568109017.stg"
              imagePullPolicy: IfNotPresent
              command: ["/docker-entrypoint.sh"]
              # NOTE: always returning successful exit code to prevent triggering of additional alerts
              # as well as leave it to human judgement whether should it be retried or not.
              args:
                - su
                - -s
                - /bin/sh
                - -c
                - |
                  set -x
                  JOB_ID=$(echo "${APP_ARGO_EVENTS_POD_NAME}" | cut -d- -f1)
                  cd /var/cordial; php artisan Job:run $JOB_ID
                  code=$?
                  # shutdown statsd exporter sidecar
                  curl --retry 5 --retry-all-errors --silent -X POST 0.0.0.0:9122/-/quit
                  # shutdown linkerd-proxy sidecar
                  curl --retry 5 --retry-all-errors --silent -X POST 127.0.0.1:4191/shutdown
                  # shutdown client-log sidecar
                  touch /mnt/exit-notice/main-container-terminated
                  echo "job $JOB_ID completed with exit code $code"
                  exit 0
                - www-data
              env:
                - name: DATADOG_HOST
                  value: "127.0.0.1"
                - name: DATADOG_PORT
                  value: "9125"
                - name: DD_ENTITY_ID
                  valueFrom:
                      fieldRef:
                          fieldPath: metadata.uid
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: APP_SECRETS_MOUNT_PATH
                  value: "/mnt/clusters-creds"
                - name: APP_ARGO_EVENTS_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: "APP_LOG_STREAMING"
                  value: "true"
              resources:
                limits:
                  ephemeral-storage: 5Gi
                  memory: 256Mi
                requests:
                  cpu: 200m
                  ephemeral-storage: 1Gi
                  memory: 256Mi
              volumeMounts:
                - name: vault-token
                  mountPath: /home/vault
                - name: vault-agent-config
                  mountPath: /etc/vault
                  readOnly: true
                - name: cordial-data
                  mountPath: /var/cordial/cordial_data
                - name: consul-template-out
                  mountPath: /var/cordial/cordial_data/config
                - name: logs
                  mountPath: /var/cordial/cordial_data/storage/logs
                - name: temp
                  mountPath: /tmp
                - name: logs-local
                  mountPath: /var/cordial/cordial_data/logs
                - name: exit-notice
                  mountPath: /mnt/exit-notice
                - name: workers-clusters-creds
                  mountPath: '/mnt/clusters-creds'
                  readOnly: true
                
                - name: php-ini-settings
                  mountPath: /usr/local/etc/php/conf.d/zz-custom.ini
                  subPath: zz-custom.ini
                - name: php-opcache
                  mountPath: /var/tmp/php-opcache
            - name: statsd-exporter
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/statsd-exporter:v0.22.7"
              imagePullPolicy: IfNotPresent
              args:
                - --web.listen-address=0.0.0.0:9122
                - --statsd.listen-udp=0.0.0.0:9125
                - --statsd.listen-tcp=0.0.0.0:9125
                - --web.enable-lifecycle
                - --statsd.mapping-config=/mnt/config/mappings.yml
                - --statsd.relay.address=$(DATADOG_HOST):8125
              env:
                - name: DATADOG_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              # the sleep keeps the exporter up while the app shuts down
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sleep
                      - "30"
              ports:
                - containerPort: 9125
                  name: tcp-statsd
                  protocol: TCP
                - containerPort: 9125
                  name: udp-statsd
                  protocol: UDP
                - containerPort: 9122
                  name: metrics
                  protocol: TCP
              volumeMounts:
                - name: statsd-exporter-config
                  mountPath: /mnt/config
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /-/healthy
                  port: metrics
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              livenessProbe:
                failureThreshold: 4
                httpGet:
                  path: /-/healthy
                  port: metrics
                  scheme: HTTP
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 150Mi
                requests:
                  cpu: 5m
                  ephemeral-storage: 100Ki
                  memory: 25Mi
            - name: client-log
              image: "960048260646.dkr.ecr.us-west-2.amazonaws.com/busybox:latest"
              imagePullPolicy: IfNotPresent
              # note: this requires the logfiles to exist first, handled inside core container itself
              args:
                - /bin/sh
                - -c
                - |
                  trap "echo caught shutdown signal; exit" TERM INT
                  tail -n+1 -F /mnt/logs/clients/*.log &
                  CHILD_PID=$!
                  (while true; do if [[ -f "/mnt/exit-notice/main-container-terminated" ]]; then kill $CHILD_PID; fi; sleep 1; done) &
                  wait $CHILD_PID
                  if [[ -f "/mnt/exit-notice/main-container-terminated" ]]; then exit 0; fi
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sleep
                      - "30"
              resources:
                requests:
                  cpu: 5m
                  memory: 25Mi
                  ephemeral-storage: 1000Mi
                limits:
                  cpu: 50m
              volumeMounts:
                - name: logs
                  mountPath: /mnt/logs
                - name: exit-notice
                  mountPath: /mnt/exit-notice
          dnsPolicy: "ClusterFirst"
          dnsConfig:
            options:
            - name: ndots
              value: "1"
            - name: single-request-reopen
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: karpenter.sh/capacity-type
                    operator: In
                    values:
                    - on-demand
```
karpenter provisioner spec:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [ "us-west-2a"]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
      - c5
      - c5d
      - c5a
      - c5ad
      - c6
      - c6a
      - c6i
      - c6id
      - c6g
      - c6gd
      - c7g
      - m5
      - m5d
      - m5a
      - m5ad
      - m6a
      - m6i
      - m6id
      - m6g
      - m6gd
      - m7g
      - r5
      - r5d
      - r5a
      - r5ad
      - r6a
      - r6i
      - r6id
      - r6g
      - r6gd
      - r7g
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values:
      - nano
      - micro
      - small
      - 8xlarge
      - 12xlarge
      - 16xlarge
      - 18xlarge
      - 24xlarge
      - 32xlarge
      - 48xlarge
      - metal
  limits:
    resources:
      cpu: "500"
      memory: 4Ti
  providerRef:
    name: cordial-bottlerocket
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 604800 # 7 days
```

**Event logs**
<img width="1765" alt="Screenshot 2023-03-15 at 16 55 50" src="https://user-images.githubusercontent.com/201724/225349225-e579c304-7653-4ac7-a2e7-07c2ebe4d7aa.png">
**Karpenter logs**
<img width="1864" alt="Screenshot 2023-03-15 at 16 58 40" src="https://user-images.githubusercontent.com/201724/225349847-a839ba05-01bc-4aea-b025-680ed77a58a9.png">

Looks only the first init container ran before pod gets evicted

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Consolidation could short-circuit before the do-not-evict annotation which would allow an eviction even if a do-not-evict label is applied:

1. If the pod is currently Terminating (i.e. if there's a DeletionTimestamp set on the pod)
2. If the pod is in a terminal state (i.e. pod.Status.Phase == Failed or Succeeded
3. If the pod is Owned by the node (i.e. has an owner reference to the Node)

Do you know what state your Pods were in when consolidation took action?

**Comment by dschaaff** [comment]
The owner refs are set to the job ```ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: 6413756a2ac1012a1c04a6cd-pqckj
    uid: 83544619-80ae-4b0a-8eaa-d2c2d175b772```
    
    We're working to gather more info on 1 and 2.

**Comment by bwagner5** [comment]
There's a window for a race to occur such that consolidation doesn't see the pods on the node before it triggers the termination workflow. A pod could schedule on the node during this window with the do-not-evict annotation and the workflow would terminate the node anyways. 

Have you considered adding a PDB to match your job pods? This would mostly prevent this race from happening since the K8s eviction API wouldn't allow us to evict the pod.

**Comment by dschaaff** [comment]
I haven't caught a pod prior to being evicted yet. Here is what we see happening in the event output though.

```
FirstSeen              LastSeen               Count   From                Type     Reason      Message
2023-03-16T20:25:41Z   2023-03-16T20:25:41Z   1       default-scheduler   Normal   Scheduled   Successfully assigned workers/64137b45d8d110a557009079-7vb77-wg6jg to ip-10-20-27-64.us-west-2.compute.internal
2023-03-16T20:25:42Z   2023-03-16T20:25:42Z   1       kubelet             Normal   Pulled      Container image "960048260646.dkr.ecr.us-west-2.amazonaws.com/cordial/core:cli-r-20230316.3945928676.stg" already present on machine
2023-03-16T20:25:42Z   2023-03-16T20:25:42Z   1       kubelet             Normal   Created     Created container config-template-copy
2023-03-16T20:25:42Z   2023-03-16T20:25:42Z   1       kubelet             Normal   Started     Started container config-template-copy
2023-03-16T20:25:52Z   2023-03-16T20:25:52Z   1       karpenter           Normal   Evicted     Evicted pod
2023-03-16T20:25:52Z   2023-03-16T20:25:52Z   1       kubelet             Normal   Killing     Stopping container config-template-copy
```

Karpenter appears to evict the pod for consolidation while the first init container is running. 

```
karpenter-77f55948d6-plcgj controller 2023-03-16T20:16:06.164Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "default", "id": "i-0c654828d13582eb5", "hostname": "ip-10-20-27-64.us-west-2.compute.internal", "instance-type": "c6g.xlarge", "zone": "us-west-2a", "capacity-type": "on-demand"}
karpenter-77f55948d6-plcgj controller 2023-03-16T20:25:51.866Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 nodes ip-10-20-27-64.us-west-2.compute.internal/c6g.xlarge/on-demand	{"commit": "dc3af1a"}
karpenter-77f55948d6-plcgj controller 2023-03-16T20:25:51.876Z	INFO	controller.termination	cordoned node	{"commit": "dc3af1a", "node": "ip-10-20-27-64.us-west-2.compute.internal"}
karpenter-77f55948d6-plcgj controller 2023-03-16T20:27:24.287Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-20-27-64.us-west-2.compute.internal"}
```

I'm running a bunch of jobs over and over trying to trigger the condition right now and of course a watched pot never boils. If a I catch an eviction before I have to leave I'll be able to share the pod's Phase at the time of eviction.

> Have you considered adding a PDB to match your job pods? This would mostly prevent this race from happening since the K8s eviction API wouldn't allow us to evict the pod.

I hadn't though of this but it is a good work around. We plan to add a pdb tomorrow for these.

**Comment by dschaaff** [comment]
Ok, I did manage to catch one. It was again evicted while the first init container was running. The pod phase set to pending according to kubectl.

```64139ea88ba920d78c0b665a-l8kxg-7x97n               Pending```

```FirstSeen              LastSeen               Count   From                Type     Reason      Message
2023-03-16T22:58:01Z   2023-03-16T22:58:01Z   1       default-scheduler   Normal   Scheduled   Successfully assigned workers/64139ea88ba920d78c0b665a-l8kxg-7x97n to ip-10-20-30-244.us-west-2.compute.internal
2023-03-16T22:58:02Z   2023-03-16T22:58:02Z   1       kubelet             Normal   Pulled      Container image "960048260646.dkr.ecr.us-west-2.amazonaws.com/cordial/core:cli-r-20230316.3945928676.stg" already present on machine
2023-03-16T22:58:02Z   2023-03-16T22:58:02Z   1       kubelet             Normal   Created     Created container config-template-copy
2023-03-16T22:58:02Z   2023-03-16T22:58:02Z   1       kubelet             Normal   Started     Started container config-template-copy
2023-03-16T22:58:16Z   2023-03-16T22:58:16Z   1       karpenter           Normal   Evicted     Evicted pod
2023-03-16T22:58:16Z   2023-03-16T22:58:16Z   1       kubelet             Normal   Killing     Stopping container config-template-copy
2023-03-16T22:58:29Z   2023-03-16T22:58:29Z   1       kubelet             Normal   Killing     Stopping container config-template-copy```

```karpenter-77f55948d6-plcgj controller 2023-03-16T22:06:48.654Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "dc3af1a", "provisioner": "default", "id": "i-034a31023d9c5c600", "hostname": "ip-10-20-30-244.us-west-2.compute.internal", "instance-type": "c6g.xlarge", "zone": "us-west-2a", "capacity-type": "on-demand"}
karpenter-77f55948d6-plcgj controller 2023-03-16T22:15:08.408Z	DEBUG	controller.node	discovered EC2 instance types	{"commit": "dc3af1a", "node": "ip-10-20-30-244.us-west-2.compute.internal", "instance-type-count": 621}
karpenter-77f55948d6-plcgj controller 2023-03-16T22:40:16.062Z	DEBUG	controller.node	discovered EC2 instance types	{"commit": "dc3af1a", "node": "ip-10-20-30-244.us-west-2.compute.internal", "instance-type-count": 621}
karpenter-77f55948d6-plcgj controller 2023-03-16T22:58:16.598Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 nodes ip-10-20-30-244.us-west-2.compute.internal/c6g.xlarge/on-demand	{"commit": "dc3af1a"}
karpenter-77f55948d6-plcgj controller 2023-03-16T22:58:16.612Z	INFO	controller.termination	cordoned node	{"commit": "dc3af1a", "node": "ip-10-20-30-244.us-west-2.compute.internal"}
karpenter-77f55948d6-plcgj controller 2023-03-16T22:59:49.202Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-20-30-244.us-west-2.compute.internal"}```

**Comment by brainiac84** [comment]
> Have you considered adding a PDB to match your job pods? This would mostly prevent this race from happening since the K8s eviction API wouldn't allow us to evict the pod.

PDB seems to be is not supported for the jobs: 
```
Name:             workers-pdb
Namespace:        workers
Max unavailable:  0
Selector:         app.kubernetes.io/name=workers-job
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              0
    Total:                0
Events:
  Type     Reason                           Age                        From               Message
  ----     ------                           ----                       ----               -------
  Warning  CalculateExpectedPodCountFailed  3m20s (x23630 over 4h13m)  controllermanager  Failed to calculate the number of expected pods: jobs.batch does not implement the scale subresource
```

**Comment by dschaaff** [comment]
Found the answer to that https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors. You can only use `minAvailable` with an integer value for pods not controlled by a Deployment, ReplicationController, ReplicaSet, or StatefulSet.

**Comment by dschaaff** [comment]
Lots of context on why the pdb work around doesn't work in slack https://kubernetes.slack.com/archives/C02SFFZSA2K/p1678987619575379

**Comment by njtran** [comment]
Quick summary: Consolidation has a 15 second wait in between computing consolidation decisions, but then doesn't check for these pods properly after that wait. The fix is to cordon the node before the TTL and checking for these pods after. I'll get this fix in hopefully today or tomorrow.

**Comment by brainiac84** [comment]
After upgrade to 0.27.1 things looks in better state, out of 5k of k8s jobs only 20 failed for last 2 days, but it seems some of the nodes gets deprovisioned by karpenter when pod scheduled on the node
<img width="2506" alt="Screenshot 2023-04-03 at 14 41 51" src="https://user-images.githubusercontent.com/201724/229499381-3479662e-9a4f-4056-8003-531e2a59946d.png">
karpenter logs around that time
```
2023-04-03T10:29:31.619Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "7131be2-dirty", "provisioner": "workers", "id": "i-0579967145eaeb0d9", "hostname": "ip-10-20-12-164.us-west-2.compute.internal", "instance-type": "c6g.large", "zone": "us-west-2a", "capacity-type": "on-demand"}
2023-04-03T10:30:03.568Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "7131be2-dirty", "pods": 14}
2023-04-03T10:30:03.568Z	INFO	controller.provisioner	computed new machine(s) to fit pod(s)	{"commit": "7131be2-dirty", "machines": 1, "pods": 10}
2023-04-03T10:30:03.568Z	INFO	controller.provisioner	computed 1 unready node(s) will fit 4 pod(s)	{"commit": "7131be2-dirty"}
2023-04-03T10:30:03.568Z	INFO	controller.provisioner	launching machine with 10 pods requesting {"cpu":"3700m","ephemeral-storage":"20726760Ki","memory":"4502Mi","pods":"19"} from types r6gd.2xlarge, r6a.xlarge, m6id.xlarge, m7g.4xlarge, c6i.4xlarge and 85 other(s)	{"commit": "7131be2-dirty", "provisioner": "workers"}
2023-04-03T10:30:05.672Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "7131be2-dirty", "provisioner": "workers", "id": "i-000345e5d11031221", "hostname": "ip-10-20-11-141.us-west-2.compute.internal", "instance-type": "c6g.xlarge", "zone": "us-west-2a", "capacity-type": "on-demand"}
2023-04-03T10:32:08.233Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "7131be2-dirty", "pods": 1}
2023-04-03T10:32:08.233Z	INFO	controller.provisioner	computed new machine(s) to fit pod(s)	{"commit": "7131be2-dirty", "machines": 1, "pods": 1}
2023-04-03T10:32:08.233Z	INFO	controller.provisioner	launching machine with 1 pods requesting {"cpu":"910m","ephemeral-storage":"2072676Ki","memory":"1568Mi","pods":"10"} from types r6gd.2xlarge, r6a.xlarge, m6id.xlarge, m6gd.xlarge, r6g.large and 85 other(s)	{"commit": "7131be2-dirty", "provisioner": "workers"}
2023-04-03T10:32:10.537Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "7131be2-dirty", "provisioner": "workers", "id": "i-07f40f9c6b665d63f", "hostname": "ip-10-20-2-129.us-west-2.compute.internal", "instance-type": "c6g.large", "zone": "us-west-2a", "capacity-type": "on-demand"}
2023-04-03T10:32:36.113Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "7131be2-dirty", "pods": 5}
--
2023-04-03T10:34:05.660Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 machines ip-10-20-12-164.us-west-2.compute.internal/c6g.large/on-demand	{"commit": "7131be2-dirty"}
2023-04-03T10:34:05.674Z	INFO	controller.termination	cordoned node	{"commit": "7131be2-dirty", "node": "ip-10-20-12-164.us-west-2.compute.internal"}
2023-04-03T10:34:05.994Z	INFO	controller.termination	deleted node	{"commit": "7131be2-dirty", "node": "ip-10-20-12-164.us-west-2.compute.internal"}
2023-04-03T10:35:26.353Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 machines ip-10-20-2-129.us-west-2.compute.internal/c6g.large/on-demand	{"commit": "7131be2-dirty"}
2023-04-03T10:35:26.372Z	INFO	controller.termination	cordoned node	{"commit": "7131be2-dirty", "node": "ip-10-20-2-129.us-west-2.compute.internal"}
2023-04-03T10:35:26.678Z	INFO	controller.termination	deleted node	{"commit": "7131be2-dirty", "node": "ip-10-20-2-129.us-west-2.compute.internal"}
```

**Comment by njtran** [comment]
Sorry I don't think I understand. It sounds like everything is working as expected? Feel free to re-open the issue if you think the issue hasn't been fully remediated.

**Comment by noxjonas** [comment]
not sure this is solved. I am still seeing evictions by karpenter (`v0.27.1`) of pods annotated with `do-not-evict`. It seems to happen many times less often, so it does work, but karpenter still ends up evicting them sometimes. I see this in events (truncated):
```
Involved Object:
  API Version:   v1
  Kind:          Pod
Kind:            Event
Last Timestamp:  2023-06-02T13:35:56Z
Message:         Evicted pod
Metadata:
    Manager:          karpenter
    Operation:        Update
    Time:             2023-06-02T13:35:56Z
Reason:               Evicted
Reporting Component:  
Reporting Instance:   
Source:
  Component:  karpenter
Type:         Normal
```

**Comment by jonathan-innis** [comment]
> karpenter still ends up evicting them sometimes.

Do you know if these pods are on nodes that are affected by [interruption](https://karpenter.sh/preview/concepts/deprovisioning/#interruption) or manual deletion. These are considered "forceful" cases where we can't stop the node deletion, so we'll ignore the pod annotations in this case.

**Comment by mollymcclean** [comment]
I am also still seeing this (`v0.28.1`), where pods with the `do-not-evict` annotation are being evicted due to consolidation of the node.

Kubernetes events
```
56m         Normal    Scheduled                pod/job1-pod1               Successfully assigned application/job1-pod1 to ip-10-1-128-242.eu-south-1.compute.internal
56m         Normal    Pulled                   pod/job1-pod1               Container image "xxx" already present on machine
56m         Normal    Created                  pod/job1-pod1               Created container cronjob
56m         Normal    Evicted                  pod/job1-pod1               Evicted pod
56m         Normal    Started                  pod/job1-pod1               Started container cronjob
56m         Normal    Killing                  pod/job1-pod1               Stopping container cronjob
56m         Normal    Scheduled                pod/job1-pod2               Successfully assigned application/job1-pod2 to ip-10-1-138-206.eu-south-1.compute.internal
56m         Normal    Pulled                   pod/job1-pod2               Container image "xxx" already present on machine
56m         Normal    Created                  pod/job1-pod2               Created container cronjob
56m         Normal    Started                  pod/job1-pod2               Started container cronjob
56m         Normal    SuccessfulCreate         job/job1                     Created pod: job1-pod1
56m         Normal    SuccessfulCreate         job/job1                     Created pod: job1-pod2
55m         Normal    Completed                job/job1                     Job completed
```

Controller Logs
```
2023-08-03T08:02:01.102Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 machines ip-10-1-128-242.eu-south-1.compute.internal/r5a.4xlarge/on-demand	{"commit": "30fa8f3-dirty"}
2023-08-03T08:02:01.195Z	INFO	controller.termination	cordoned node	{"commit": "30fa8f3-dirty", "node": "ip-10-1-128-242.eu-south-1.compute.internal"}
```

**Comment by gnuletik** [comment]
Same issue here with Karpenter `v0.29.2`.

We had a:
- `15:46:49`: job created with the `do-not-evict` annotation on the pod
- `15:46:55`: pod marked as ready
- `15:47:02`: Karpenter deprovisionned the node

```
karpenter karpenter-67bff84dd9-hgbr8 controller 2023-08-08T15:47:02.380Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 machines ip-xxx	{"commit": "34d50bf-dirty"}
karpenter karpenter-67bff84dd9-hgbr8 controller 2023-08-08T15:47:02.471Z	INFO	controller.termination	cordoned node	{"commit": "34d50bf-dirty", "node": "ip-xxx"}
karpenter karpenter-67bff84dd9-hgbr8 controller 2023-08-08T15:47:15.387Z	INFO	controller.termination	deleted node	{"commit": "34d50bf-dirty", "node": "ip-xxx"}
karpenter karpenter-67bff84dd9-hgbr8 controller 2023-08-08T15:47:15.664Z	INFO	controller.machine.termination	deleted machine	{"commit": "34d50bf-dirty", "machine": "tasks-kqdgs", "node": "ip-xxx", "provisioner": "tasks", "provider-id": "xxx"}
```

Can you consider reopening the issue?

**Comment by ellistarn** [comment]
For future readers, we're following this issue here: https://github.com/aws/karpenter/issues/4310
